# Generated by Django 5.0.2 on 2024-02-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_task_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
