# Generated by Django 5.0.2 on 2024-02-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_alter_task_file_alter_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
