# Generated by Django 5.0.2 on 2024-03-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_alter_task_file_alter_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hash',
            name='hashed',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date added'),
        ),
    ]
