# Generated by Django 5.0.2 on 2024-03-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_alter_hash_hashed_alter_list_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='todolist.task'),
        ),
    ]
