# Generated by Django 5.0.2 on 2024-03-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0010_alter_task_file_alter_task_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hash',
        ),
    ]
