# Generated by Django 5.0.2 on 2024-03-06 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0011_delete_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='lists',
        ),
        migrations.AddField(
            model_name='list',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
