# Generated by Django 5.0.2 on 2024-03-06 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0012_remove_customuser_lists_list_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='IntermediaryListTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('List', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='todolist.list')),
                ('Task', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='todolist.task')),
            ],
        ),
    ]
