# Generated by Django 5.0.2 on 2024-03-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0013_task_creator_intermediarylisttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
