# Generated by Django 5.0.2 on 2024-03-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0014_alter_task_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='url',
            field=models.URLField(default=None),
        ),
    ]
