# Generated by Django 5.0.2 on 2024-03-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0015_task_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
