# Generated by Django 5.0.2 on 2024-03-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0016_alter_task_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntermediaryListTask',
            new_name='IntermediaryTodoListTask',
        ),
        migrations.RenameModel(
            old_name='List',
            new_name='TodoList',
        ),
    ]
