# Generated by Django 5.0.2 on 2024-02-20 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('done', models.BooleanField(default=False)),
                ('importance', models.IntegerField()),
                ('date_added', models.DateTimeField(verbose_name='date added')),
                ('deadline', models.DateField(verbose_name='deadline')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.list')),
            ],
            options={
                'ordering': ('date_added', 'importance'),
            },
        ),
    ]
