# Generated by Django 5.0.2 on 2024-02-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, to='todolist.task'),
        ),
    ]
