# Generated by Django 5.0.2 on 2024-03-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldict',
            name='original_url',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
