# Generated by Django 5.0.2 on 2024-03-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0003_alter_urldict_original_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldict',
            name='original_url',
            field=models.CharField(max_length=500),
        ),
    ]
